"use client";
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, ScatterChart, Scatter, Cell } from "recharts";
import { scoreCompetitor } from "@/lib/analysis";
import type { Competitor } from "@/lib/model";
const colors=["#426d49","#98ac7c","#d3be8d"];
export function MarketCharts({rows}:{rows:Competitor[]}) {
  const ratings=[{name:"Under 3",count:0},{name:"3.0–3.9",count:0},{name:"4.0–4.4",count:0},{name:"4.5–5.0",count:0},{name:"Unrated",count:0}];
  rows.forEach(p=>ratings[p.rating==null?4:p.rating<3?0:p.rating<4?1:p.rating<4.5?2:3].count++);
  const reviews=rows.filter(p=>p.userRatingCount!=null).sort((a,b)=>b.userRatingCount!-a.userRatingCount!).slice(0,6).map(p=>({name:p.name,reviews:p.userRatingCount}));
  const scatter=rows.filter(p=>p.rating!=null && p.userRatingCount!=null).map(p=>({name:p.name,rating:p.rating,reviews:p.userRatingCount}));
  const distances=[{name:"0–1 km",count:0},{name:"1–3 km",count:0},{name:"3–5 km",count:0},{name:"Unknown",count:0}];
  rows.forEach(p=>distances[p.distance==null?3:p.distance<=1?0:p.distance<=3?1:2].count++);
  const strengths=["Strong","Moderate","Emerging"].map(name=>({name,count:rows.filter(p=>scoreCompetitor(p).strength===name).length}));
  if(!rows.length) return <div className="chart-empty">No competitors in this view. Adjust your filters or selection.</div>;
  return <div className="charts-grid">
    <ChartCard title="Rating distribution" subtitle="How competitors are rated" description={ratings.map(x=>`${x.name}: ${x.count}`).join(", ")}><ResponsiveContainer width="100%" height={230}><BarChart data={ratings}><CartesianGrid vertical={false} stroke="#edf0e8"/><XAxis dataKey="name" tick={{fontSize:12}} axisLine={false} tickLine={false}/><YAxis allowDecimals={false} width={30} tick={{fontSize:12}} axisLine={false} tickLine={false}/><Tooltip/><Bar dataKey="count" name="Competitors" fill="#55794e" radius={[4,4,0,0]} maxBarSize={45}/></BarChart></ResponsiveContainer></ChartCard>
    <ChartCard title="Most reviewed competitors" subtitle="Top six in the current view" description={reviews.map(x=>`${x.name}: ${x.reviews} reviews`).join(", ")}><ResponsiveContainer width="100%" height={230}><BarChart data={reviews} layout="vertical" margin={{left:0,right:25}}><CartesianGrid horizontal={false} stroke="#edf0e8"/><XAxis type="number" tick={{fontSize:12}} axisLine={false} tickLine={false}/><YAxis type="category" dataKey="name" width={135} tick={{fontSize:12}} axisLine={false} tickLine={false}/><Tooltip/><Bar dataKey="reviews" name="Reviews" fill="#8ea576" radius={[0,4,4,0]} maxBarSize={20}/></BarChart></ResponsiveContainer></ChartCard>
    <ChartCard title="Rating vs. review count" subtitle="Only competitors with both values" description={`${scatter.length} competitors have ratings and review counts.`}><ResponsiveContainer width="100%" height={240}><ScatterChart margin={{bottom:20,right:20}}><CartesianGrid stroke="#edf0e8"/><XAxis type="number" dataKey="reviews" name="Reviews" tick={{fontSize:12}} label={{value:"Review count",position:"bottom",fontSize:12}}/><YAxis type="number" dataKey="rating" name="Rating" domain={[0,5]} width={35} tick={{fontSize:12}}/><Tooltip cursor={{strokeDasharray:"3 3"}} content={({active,payload})=>{const p=payload?.[0]?.payload;return active&&p?<div className="chart-tooltip"><strong>{p.name}</strong><br/>{p.rating} stars · {p.reviews} reviews</div>:null;}}/><Scatter data={scatter} fill="#537b4e"/></ScatterChart></ResponsiveContainer></ChartCard>
    <ChartCard title="Competitors by distance" subtitle="Straight-line distance from your territory center" description={distances.map(x=>`${x.name}: ${x.count}`).join(", ")}><ResponsiveContainer width="100%" height={240}><BarChart data={distances}><CartesianGrid vertical={false} stroke="#edf0e8"/><XAxis dataKey="name" tick={{fontSize:12}} axisLine={false} tickLine={false}/><YAxis allowDecimals={false} width={30} tick={{fontSize:12}} axisLine={false} tickLine={false}/><Tooltip/><Bar dataKey="count" name="Competitors" fill="#a8b991" radius={[4,4,0,0]} maxBarSize={58}/></BarChart></ResponsiveContainer></ChartCard>
    <ChartCard title="Competitor strength" subtitle="Observed listing presence, using the published heuristic" description={strengths.map(x=>`${x.name}: ${x.count}`).join(", ")}><ResponsiveContainer width="100%" height={220}><BarChart data={strengths} layout="vertical"><XAxis type="number" allowDecimals={false} tick={{fontSize:12}} axisLine={false}/><YAxis type="category" dataKey="name" width={85} tick={{fontSize:12}} axisLine={false} tickLine={false}/><Tooltip/><Bar dataKey="count" name="Competitors" radius={[0,5,5,0]} maxBarSize={30}>{strengths.map((x,i)=><Cell key={x.name} fill={colors[i]}/>)}</Bar></BarChart></ResponsiveContainer></ChartCard>
  </div>;
}
function ChartCard({title,subtitle,description,children}:{title:string;subtitle:string;description:string;children:React.ReactNode}) {return <section className="chart-card" aria-label={`${title}. ${description}`}><h3>{title}</h3><p>{subtitle}</p>{children}</section>;}
